server:
  http:
    host: "0.0.0.0"
    port: "8080"

db:
  postgres:
    dialect: "postgres"
    dsn: "host=localhost user=postgres password= dbname=postgres port=5432 sslmode=disable"
    maxConnLifetimeMinute: 3
    maxConn: 10

repository:
  type: "postgres"